version: "3"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - HDFS_CONF_dfs_blocksize=67108864
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
      
#   datanode2:
#     image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#     container_name: datanode2
#     restart: always
#     volumes:
#       - hadoop_datanode:/hadoop/dfs/data
#     environment:
#       SERVICE_PRECONDITION: "namenode:9870"
#     env_file:
#       - ./hadoop.env

#   datanode3:
#     image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#     container_name: datanode3
#     restart: always
#     volumes:
#       - hadoop_datanode:/hadoop/dfs/data
#     environment:
#       SERVICE_PRECONDITION: "namenode:9870"
#     env_file:
#       - ./hadoop.env
  
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    volumes:
      - ./ram_time_values.csv:/output/ram_time_values.csv
      - ./dt_model.pkl:/output/dt_model.pkl
      - ./simple_script_not_parallel.py:/scripts/simple_script_not_parallel.py
      - ./simple_script_parallel.py:/scripts/simple_script_parallel.py
    command: spark-class org.apache.spark.deploy.master.Master
    ports:
      - 9090:8080
      - 7077:7077
    environment:
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    deploy:
      resources:
        limits:
          memory: 7G
  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

volumes:
  hadoop_namenode:
  hadoop_datanode:
